### ISSUE TITLE
[NOT AN ISSUE] What theme is being used in the screenshot attached to the README?

### ISSUE THREAD

**Issue by Irastris** [muerrilla/sd-webui-detail-daemon#11]
Sorry to make an issue for this, but I could not find another means of contacting you. I was curious what WebUI theme is being used in the screenshot of the extension's panel in the README. Thanks!

![346371805-045574cb-465c-4991-83c4-d02f803a330b](https://github.com/user-attachments/assets/cd23b0d1-8785-4498-871b-fed2b50d7930)

**Comment by muerrilla** [comment]
> I was curious what WebUI theme is being used in the screenshot of the extension's panel in the README. Thanks!

Hey there. It's a custom css I made for myself. Don't mind sharing it (with no compatibility guarantees) but I'm on vacation right now. Can do it in a month or so.

**Comment by Irastris** [comment]
That'd be awesome! It looks really elegant so I'd greatly appreciate its distribution.

**Comment by muerrilla** [comment]
Here you go:
[sd-webui-neutrino](https://github.com/muerrilla/sd-webui-neutrino)

**Comment by Irastris** [comment]
Awesome!
