### ISSUE TITLE
Does this work with Flux models?

### ISSUE THREAD

**Issue by Jonseed** [muerrilla/sd-webui-detail-daemon#13]
I tested it with Flux, and it doesn't seem to change much about the picture when adjusting the detail amount. Perhaps the Flux architecture works differently?

**Comment by Jonseed** [comment]
Looks like some have had success injecting noise for Flux in this way: https://www.reddit.com/r/StableDiffusion/comments/1fue0oe/a_noise_injection_method_for_flux_v2/

**Comment by muerrilla** [comment]
It does indeed work with flux. You just need to use stronger values than with SD.
![00053-16763983172](https://github.com/user-attachments/assets/e58349d0-f37c-44f8-b933-28527c8bc784)
![00053-1676398317](https://github.com/user-attachments/assets/f927dfb9-3c59-4f2b-b571-9d66c64865d3)
