### ISSUE TITLE
Feature request: ComfyUI nodes

### ISSUE THREAD

**Issue by Jonseed** [muerrilla/sd-webui-detail-daemon#14]
It would be great if this could be used as a node in ComfyUI. I'm not sure if there is anything like it in ComfyUI. There are many nodes that say they can adjust the noise in your workflow, such as [ComfyUI_Noise](https://github.com/BlenderNeko/ComfyUI_Noise), but I'm not sure they do it like Detail Daemon.

**Comment by muerrilla** [comment]
Gotta look for nodes that allow you to set your own sigmas or adjust the existing schedules. I'm pretty sure there are many out there.

**Comment by Jonseed** [comment]
There is this node, [CustomScheduler](https://github.com/BlakeOne/ComfyUI-CustomScheduler), that lets you set the sigmas at each step, but how would I use it to achieve what Detail Daemon does? Set each step sigma individually?

**Comment by Jonseed** [comment]
I wonder if this [CADS function](https://github.com/asagi4/ComfyUI-CADS) is similar to Detail Daemon (also available as an [extension in Auto1111](https://github.com/v0xie/sd-webui-cads)). Or is that something completely different than Detail Daemon? It claims to increase diversity of outputs, not necessarily add detail.

**Comment by blepping** [comment]
ComfyUI users can give this small sampler wrapper a shot: <https://gist.github.com/blepping/50103df387945b3fb2691a46812b4a64>

put the file in `custom_nodes`, it will add a `LyingSigmaSampler` node. nothing special to use it:

![image](https://github.com/user-attachments/assets/a161dc17-4876-4647-bc8c-aab922905267)

the sigma just gets multiplied by `1 * dishonesty_factor` so for example `1 + -0.05` is 0.95 - we reduced the sigma by 5%. you can also chain them if you want to use different factors at different points in sampling (negative values will add detail, positive will generally smooth things out). random example:

![image](https://github.com/user-attachments/assets/33f9a33b-43f5-4be6-8f80-c1b07497f3fc)

it should work with most samplers/models.

**Comment by muerrilla** [comment]
> I wonder if this [CADS function](https://github.com/asagi4/ComfyUI-CADS) is similar to Detail Daemon

It is not. As far as I understand CADS is degrading the **conditioning tensor** by adding noise to it at early sampling steps, which leads to more diverse output over different seeds. DD adjusts the sigmas which affect how much the **image latent tensor** is denoised at each step, affecting the amount of detail in the image.

**Comment by muerrilla** [comment]
> ComfyUI users can give this small sampler wrapper a shot: https://gist.github.com/blepping/50103df387945b3fb2691a46812b4a64

This is the way! You can also do what [Nerdy is doing here](https://www.youtube.com/watch?v=Sc6HbNjUlgI) if you'd rather provide the list of sigmas than chaining up those nodes.

**Comment by muerrilla** [comment]
> i don't think you can do it by just manipulating sigmas. doing something like multiplying the sigmas by 0.95 or whatever is super easy in ComfyUI but that also means you're reducing how much noise is added initially.

Oh I see. That would indeed be different.

**Comment by Jonseed** [comment]
With @blepping 's great help, there is now a proper port of Detail Daemon for ComfyUI:
https://github.com/Jonseed/ComfyUI-Detail-Daemon

Thank you @muerrilla for your great original work on this!
