### ISSUE TITLE
Does not work with forge.

### ISSUE THREAD

**Issue by derVedro** [muerrilla/sd-webui-detail-daemon#3]
I I tried to test your extension (e6ad605) with latest [forge](https://github.com/lllyasviel/stable-diffusion-webui-forge) (29be1da7) UI and got a few exceptions like that:

```python
*** Error executing callback cfg_denoiser_callback for /mnt/SSD/neuro/forge/extensions/sd-webui-detail-daemon/scripts/detail_daemon.py                         | 7/25 [00:04<00:11,  1.56it/s]
    Traceback (most recent call last):
      File "/mnt/SSD/neuro/forge/modules/script_callbacks.py", line 233, in cfg_denoiser_callback
        c.callback(params)
      File "/mnt/SSD/neuro/forge/extensions/sd-webui-detail-daemon/scripts/detail_daemon.py", line 154, in denoiser_callback
        params.sigma[1] *= 1 - self.schedule[idx] * -.1
        ~~~~~~~~~~~~^^^
    IndexError: index 1 is out of bounds for dimension 0 with size 1
```

Is it possible to make your extension compatible with forge?

**Comment by muerrilla** [comment]
Gotta look into it later. But for now if you set mode to "both" or maybe "cond" it might work.

**Comment by marcusbob93** [comment]
> Gotta look into it later. But for now if you set mode to "both" or maybe "cond" it might work.

Yes, I confirm that "cond" and "both" both work on Forge, for now only "uncond" generates that problem.

**Comment by muerrilla** [comment]
Just got fixed.. to a degree. Forge does not allow `cond` and `uncond` modes, but it's handled more gracefully now (i.e. it automatically switches to `both` and prints a warning to console instead of throwing an error).
