### ISSUE TITLE
Positive detail values reducing details, while negative detail values are increasing details

### ISSUE THREAD

**Issue by wogam** [muerrilla/sd-webui-detail-daemon#8]
HI, thanks for creating the extension. It works really well.

Unfortunately, positive detail values reduce details, while negative detail values are increase details. See examples below.

A1111: v1.9.4
Latest commit of extension.

Prompt: A man

No DD:
![grid-0000](https://github.com/muerrilla/sd-webui-detail-daemon/assets/48340127/c1112e45-c9e5-4c1b-b556-bb075f5658ac)

DD (+0.2) [reduced details in image 2]
![grid-0004](https://github.com/muerrilla/sd-webui-detail-daemon/assets/48340127/b8e153da-b177-49a4-9248-8aa12c7020b5)

DD (-0.2) [increased details in image 2]
![grid-0006](https://github.com/muerrilla/sd-webui-detail-daemon/assets/48340127/f3006959-bae2-4dcc-93bc-4e210277fa06)

**Comment by wogam** [comment]
Update: this is only the case when creating batch images.

**Comment by muerrilla** [comment]
Thanks for reporting. Got fixed.
