### ISSUE TITLE
Doesn't seem to be doing anything :(

### ISSUE THREAD

**Issue by Jac4270** [muerrilla/sd-webui-detail-daemon#9]
So, iunno if I'm doing something wrong or not (don't think I am tho), but no matter what I do, this literally does not change the image in any way :(
Any help on this? ^^'

**Comment by muerrilla** [comment]
Gotta provide more context.

**Comment by Jac4270** [comment]
I mean, iunno what else to say about it really lol. It "works", as in there aren't any error codes shown, but no matter how I configure the settings, its the same image. It's like it's not active, even tho it is because it shows in the generation info. I thought it was maybe just the model, but it says it works for all models xp

**Comment by muerrilla** [comment]
Well, it works fine over here, so you gotta be more specific. What's your webui version, prompt, generation settings, model, etc. and what is printed on the console after  you click generate?

**Comment by Jac4270** [comment]
Webui version is 1.7.0 I believe, it happens on all prompt, and most of my settings are default except for the size, but it happens with any size too. Console is all normal too xp
It literally shows nothing about it not working, trust me, I'd love to give more detail but that's really all I have to work with lol. It seems to happen regardless of any settings, size, prompt, anything

**Comment by Jac4270** [comment]
Ah, finally got the console to say something useful! Here:

*** Error executing callback cfg_denoiser_callback for /home/me/Desktop/SD/extensions/sd-webui-detail-daemon/scripts/detail_daemon.py
    Traceback (most recent call last):
      File "/home/me/Desktop/SD/modules/script_callbacks.py", line 216, in cfg_denoiser_callback
        c.callback(params)
      File "/home/me/Desktop/SD/extensions/sd-webui-detail-daemon/scripts/detail_daemon.py", line 156, in denoiser_callback
        idx = params.denoiser.step
    AttributeError: 'CFGDenoiserParams' object has no attribute 'denoiser'

---
